package RetryFailedTestCases;

import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;

public class Retry implements IRetryAnalyzer {
    private int counter = 0;
    private int retyCounter = 0;

    @Override
    public boolean retry(ITestResult iTestResult) {
        if(counter < retyCounter){
            counter++;
            return true;
        }
        return false;

        //This much code is enough to rerun your failed test cases, but then you need to write (RetryAnalyzer = Retry.class) in front of every test annotation
        //if you don't want to write it in front of every test you can do it using IAnnotationTransformer(Transformation class)
        //You can also run your failed test cases manually by executing testng-failed.xml which was auto generated by testNG

    }
}
